### ISSUE TITLE
Filter does not work when you paste content to search using mouse

### ISSUE THREAD

**Issue by swetapatil** [PredixDev/px-data-table#79]
Expected behavior 
Filter should work when you try to filter out records by pasting content to search using mouse

Actual behavior:
Filter does not work. 
(Filter is not able to recognize right click event.)

Steps to reproduce the problem:
In filter input box paste content to search using mouse.

Environment 
I am trying to test it on px-data-table in Chrome(Version 54.0.2840.99 m) and IE(11) on Windows 7.

I am attaching screenshot to help you understand issue.
![filter](https://cloud.githubusercontent.com/assets/17895209/20832381/049f9c3c-b8b0-11e6-8181-0a2c3a8d3579.png)

**Comment by randyaskin** [comment]
Fixed in v1.15.16.

**Comment by LRagji** [comment]
Hey this Defect is still not fixed tried pasting with mouse it doesn't work; on pasting 2 times it works

**Comment by randyaskin** [comment]
Seems to be inconsistent browser behavior for the on-paste event, not sure there's a way around this.

**Comment by LRagji** [comment]
This does mean the issue is still open, is there any alternate way to
achive this? We tried W3School codepen it worked for us in first go, is
there any possibility that the datatable or its dependent framework is
eating up the first event while the second event goes through...

If we can reopen the isue that would be great for our project tracking
purpose..

**Comment by randyaskin** [comment]
By switching from on-paste / on-keyup to on-input, the filter behavior seems to be consistent now for all cases - pasting with the keyboard, pasting with the mouse, typing manually, etc. See v2.1.7.

**Comment by LRagji** [comment]
Thanks for fixing up, will validate with said version...
