### ISSUE TITLE
px-data-table : Filtering not removed after clicking on x(cross) button in IE

### ISSUE THREAD

**Issue by fsevak** [PredixDev/px-data-table#90]
Steps to replicate the issue in IE: Type any text to filter data in px-data-table. 
Click on x(cross) which is enabled on entering some text in filter. This clears the text in filter. 
Table still shows the filtered data instead of removing all filters applied on table.

**Comment by mdwragg** [comment]
Hi, can you fill in the issue according to the template please? Screen shots and OS are vital to replicate this.

**Comment by randyaskin** [comment]
Fixed in v1.15.8 by hiding the "ms-clear" (x-button).

**Comment by ChauhanVinita** [comment]
Hi,
The defect is still not fixed ."ms-clear" (x-button) will just clear the content inside filter textbox without refreshing the list in px-data-table.
Expected behavior :Px-data-table should display the list clearing the filter.

**Comment by randyaskin** [comment]
You should not have even been able to see / interact with the ms-clear button, as I hid it in v1.15.8. However, I've found that by changing from on-keyup / on-paste to on-input instead, this issue is resolved along with issue #79, so I've re-enabled the ms-clear button, which should now also update the filters when clicked.
